#!/bin/bash

fxxx  CPATH               "${CPATH}"                "$1"
fxxx  C_INCLUDE_PATH      "${C_INCLUDE_PATH}"       "x"
fxxx  CPLUS_INCLUDE_PATH  "${CPLUS_INCLUDE_PATH}"   "x"
fxxx  OBJC_INCLUDE_PATH   "${OBJC_INCLUDE_PATH}"    "x"
